apiVersion: v1
kind: Service
metadata:
  name: {{ include "rosslib.fullname" . }}-webapp
  labels:
    {{- include "rosslib.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rosslib.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
