apiVersion: v2
name: rosslib
description: A Helm chart for Rosslib application
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: 18.4.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 25.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: meilisearch
    version: 0.25.1
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    condition: meilisearch.enabled
  - name: rustfs
    version: 0.0.83
    repository: https://charts.rustfs.com/
    condition: rustfs.enabled
